apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cart
  namespace: argocd
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/RoboShop1/r-helm.git
    targetRevision: main
    helm:
      releaseName: cart
      valueFiles:
        - env-dev/cart.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true