name: Commit Comment Workflow

on:
  push:
    branches:
      - main  # Optional: Specify the branches to listen for commit comments on

jobs:
  handle_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: printenv
