name: Commit Comment Workflow

on:
  push:
    branches:
      - main  # Optional: Specify the branches to listen for commit comments on

jobs:
  handle_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        run: |
          echo "sample is ${{ github.event.head_commit.message }}"
          echo "In env ${GITHUB_EVENT_HEAD_COMMIT_MESSAGE}"
        

      - name: ok
        run: |
          echo "${{ toJSON(github) }}"
