name: one workflow
on:
  workflow_dispatch:
    inputs:
      name:
        type: string

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: sample echo
        run: |
          echo "Trigger from api - ${{ inputs.name }}"