name: two Workflow

on:
  workflow_run:
    workflows: ["one workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: print
        run: |
          echo "This is ${GITHUB_EVENT_WORKFLOW_RUN_CONCLUSION}"
          echo "same  ${GITHUB_EVENT_NAME}"
          echo "RUN ${GITHUB_RUN_NUMBER}"
          
